# -*- coding: utf-8 -*-

###################################################################
# Writer    #  Tolga AKKAPULU                                     #
# Web       #  https://www.tolgaakkapulu.com                      #
#           #  https://www.parolaanalizi.com                      #
# LinkedIN  #  https://tr.linkedin.com/in/tolga-akkapulu-518054105#
# GitHub    #  https://github.com/tolgaakkapulu                   #
###################################################################

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QThread, pyqtSignal
from PyQt5.QtWidgets import *
from Crypto.Cipher import AES
from Crypto.Hash import SHA256
from Crypto import Random
import webbrowser
from shutil import copyfile
import os

class MyThread(QThread):
    progress = pyqtSignal(int)

    def __init__(self, k):
        super().__init__()
        self.k = k

    def run(self):
        for i in range(self.k * 1001):
            sum([i * i for i in range(10)])
            ex = i // (self.k * 2)
            self.progress.emit(ex)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(680, 425)
        MainWindow.setMinimumSize(QtCore.QSize(680, 425))
        MainWindow.setMaximumSize(QtCore.QSize(680, 425))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/title.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setMinimumSize(QtCore.QSize(250, 0))
        self.graphicsView.setMaximumSize(QtCore.QSize(250, 16777215))
        self.graphicsView.setStyleSheet("background-image: url(img/left.png);")
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayout_2.addWidget(self.graphicsView, 0, 0, 1, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_4.addWidget(self.line, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(0, 0, 127);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 0, 1, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setStyleSheet("color: rgb(0, 0, 127);")
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.line_3 = QtWidgets.QFrame(self.tab_3)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_5.addWidget(self.line_3, 3, 0, 1, 2)
        self.gridLayout_13 = QtWidgets.QGridLayout()
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.pushButton_2 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_2.setEnabled(False)
        self.pushButton_2.setMinimumSize(QtCore.QSize(184, 40))
        self.pushButton_2.setMaximumSize(QtCore.QSize(1866, 40))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_13.addWidget(self.pushButton_2, 0, 0, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_4.setEnabled(False)
        self.pushButton_4.setMinimumSize(QtCore.QSize(184, 40))
        self.pushButton_4.setMaximumSize(QtCore.QSize(1866, 40))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_13.addWidget(self.pushButton_4, 0, 1, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_13, 18, 0, 1, 2)
        self.line_6 = QtWidgets.QFrame(self.tab_3)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.gridLayout_5.addWidget(self.line_6, 13, 0, 1, 2)
        self.line_7 = QtWidgets.QFrame(self.tab_3)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.gridLayout_5.addWidget(self.line_7, 17, 0, 1, 2)
        self.line_4 = QtWidgets.QFrame(self.tab_3)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout_5.addWidget(self.line_4, 8, 0, 1, 2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_6 = QtWidgets.QLabel(self.tab_3)
        self.label_6.setMinimumSize(QtCore.QSize(30, 0))
        self.label_6.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)
        self.pushButton_3 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_3.setEnabled(False)
        self.pushButton_3.setMinimumSize(QtCore.QSize(100, 20))
        self.pushButton_3.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_4.addWidget(self.pushButton_3)
        self.gridLayout_5.addLayout(self.horizontalLayout_4, 9, 0, 1, 2)
        self.gridLayout_18 = QtWidgets.QGridLayout()
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.label_10 = QtWidgets.QLabel(self.tab_3)
        self.label_10.setMinimumSize(QtCore.QSize(70, 0))
        self.label_10.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("")
        self.label_10.setObjectName("label_10")
        self.gridLayout_18.addWidget(self.label_10, 0, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.tab_3)
        self.label_11.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_11.setObjectName("label_11")
        self.gridLayout_18.addWidget(self.label_11, 0, 2, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_18, 11, 0, 1, 2)
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_5 = QtWidgets.QLabel(self.tab_3)
        self.label_5.setMinimumSize(QtCore.QSize(60, 0))
        self.label_5.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_10.addWidget(self.label_5, 0, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit.setEnabled(False)
        self.lineEdit.setMinimumSize(QtCore.QSize(308, 25))
        self.lineEdit.setMaximumSize(QtCore.QSize(308, 25))
        self.lineEdit.setStyleSheet("color: rgb(0, 0, 0);")
        self.lineEdit.setClearButtonEnabled(True)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_10.addWidget(self.lineEdit, 0, 1, 1, 1, QtCore.Qt.AlignRight)
        self.gridLayout_5.addLayout(self.gridLayout_10, 7, 0, 1, 2)
        self.gridLayout_11 = QtWidgets.QGridLayout()
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.label_7 = QtWidgets.QLabel(self.tab_3)
        self.label_7.setMinimumSize(QtCore.QSize(70, 0))
        self.label_7.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout_11.addWidget(self.label_7, 0, 0, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(self.tab_3)
        self.progressBar.setMinimumSize(QtCore.QSize(0, 20))
        self.progressBar.setMaximumSize(QtCore.QSize(308, 20))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(False)
        self.progressBar.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout_11.addWidget(self.progressBar, 0, 1, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_11, 16, 0, 1, 2)
        self.line_5 = QtWidgets.QFrame(self.tab_3)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout_5.addWidget(self.line_5, 10, 0, 1, 2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.tab_3)
        self.label_2.setEnabled(True)
        self.label_2.setMinimumSize(QtCore.QSize(30, 0))
        self.label_2.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.gridLayout_5.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton = QtWidgets.QPushButton(self.tab_3)
        self.pushButton.setMinimumSize(QtCore.QSize(100, 20))
        self.pushButton.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton, 0, QtCore.Qt.AlignRight)
        self.gridLayout_5.addLayout(self.horizontalLayout_2, 1, 1, 1, 1)
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_4 = QtWidgets.QLabel(self.tab_3)
        self.label_4.setMinimumSize(QtCore.QSize(45, 0))
        self.label_4.setMaximumSize(QtCore.QSize(45, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_7.addWidget(self.label_4, 0, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.tab_3)
        self.label_3.setMinimumSize(QtCore.QSize(70, 0))
        self.label_3.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_7.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.tab_3)
        self.label_9.setMinimumSize(QtCore.QSize(105, 0))
        self.label_9.setMaximumSize(QtCore.QSize(105, 16777215))
        self.label_9.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_7.addWidget(self.label_9, 0, 3, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.tab_3)
        self.label_8.setMinimumSize(QtCore.QSize(140, 0))
        self.label_8.setMaximumSize(QtCore.QSize(140, 16777215))
        self.label_8.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_8.setObjectName("label_8")
        self.gridLayout_7.addWidget(self.label_8, 0, 1, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_7, 4, 0, 1, 2)
        self.gridLayout_14 = QtWidgets.QGridLayout()
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.label_13 = QtWidgets.QLabel(self.tab_3)
        self.label_13.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_13.setObjectName("label_13")
        self.gridLayout_14.addWidget(self.label_13, 2, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout_14.addWidget(self.label_12, 0, 0, 1, 1)
        self.line_12 = QtWidgets.QFrame(self.tab_3)
        self.line_12.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.gridLayout_14.addWidget(self.line_12, 1, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_14, 20, 0, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem, 21, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem1, 19, 0, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.tab_3)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_5.addWidget(self.line_2, 5, 0, 1, 2)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("img/lock-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_3, icon1, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.gridLayout_27 = QtWidgets.QGridLayout()
        self.gridLayout_27.setObjectName("gridLayout_27")
        self.label_32 = QtWidgets.QLabel(self.tab_4)
        self.label_32.setMinimumSize(QtCore.QSize(30, 0))
        self.label_32.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_32.setObjectName("label_32")
        self.gridLayout_27.addWidget(self.label_32, 0, 0, 1, 1)
        self.pushButton_11 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_11.setEnabled(False)
        self.pushButton_11.setMinimumSize(QtCore.QSize(100, 20))
        self.pushButton_11.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_11.setFont(font)
        self.pushButton_11.setObjectName("pushButton_11")
        self.gridLayout_27.addWidget(self.pushButton_11, 0, 1, 1, 1, QtCore.Qt.AlignRight)
        self.gridLayout_9.addLayout(self.gridLayout_27, 8, 0, 1, 2)
        self.gridLayout_23 = QtWidgets.QGridLayout()
        self.gridLayout_23.setObjectName("gridLayout_23")
        self.label_30 = QtWidgets.QLabel(self.tab_4)
        self.label_30.setMinimumSize(QtCore.QSize(105, 0))
        self.label_30.setMaximumSize(QtCore.QSize(105, 16777215))
        self.label_30.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_30.setAlignment(QtCore.Qt.AlignCenter)
        self.label_30.setObjectName("label_30")
        self.gridLayout_23.addWidget(self.label_30, 0, 3, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.tab_4)
        self.label_29.setMinimumSize(QtCore.QSize(45, 0))
        self.label_29.setMaximumSize(QtCore.QSize(45, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.gridLayout_23.addWidget(self.label_29, 0, 2, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.tab_4)
        self.label_28.setMinimumSize(QtCore.QSize(140, 0))
        self.label_28.setMaximumSize(QtCore.QSize(140, 16777215))
        self.label_28.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_28.setObjectName("label_28")
        self.gridLayout_23.addWidget(self.label_28, 0, 1, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.tab_4)
        self.label_27.setMinimumSize(QtCore.QSize(70, 0))
        self.label_27.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.gridLayout_23.addWidget(self.label_27, 0, 0, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_23, 2, 0, 1, 2)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_26 = QtWidgets.QLabel(self.tab_4)
        self.label_26.setMinimumSize(QtCore.QSize(0, 20))
        self.label_26.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_26.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_26.setObjectName("label_26")
        self.gridLayout_6.addWidget(self.label_26, 0, 0, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_6, 0, 0, 1, 1)
        self.gridLayout_31 = QtWidgets.QGridLayout()
        self.gridLayout_31.setObjectName("gridLayout_31")
        self.label_35 = QtWidgets.QLabel(self.tab_4)
        self.label_35.setMinimumSize(QtCore.QSize(70, 0))
        self.label_35.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_35.setFont(font)
        self.label_35.setObjectName("label_35")
        self.gridLayout_31.addWidget(self.label_35, 0, 0, 1, 1)
        self.progressBar_3 = QtWidgets.QProgressBar(self.tab_4)
        self.progressBar_3.setEnabled(False)
        self.progressBar_3.setMinimumSize(QtCore.QSize(0, 20))
        self.progressBar_3.setMaximumSize(QtCore.QSize(308, 20))
        self.progressBar_3.setProperty("value", 0)
        self.progressBar_3.setTextVisible(False)
        self.progressBar_3.setObjectName("progressBar_3")
        self.gridLayout_31.addWidget(self.progressBar_3, 0, 1, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_31, 12, 0, 1, 2)
        self.line_15 = QtWidgets.QFrame(self.tab_4)
        self.line_15.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_15.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_15.setObjectName("line_15")
        self.gridLayout_9.addWidget(self.line_15, 11, 0, 1, 2)
        self.line_11 = QtWidgets.QFrame(self.tab_4)
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.gridLayout_9.addWidget(self.line_11, 1, 0, 1, 2)
        self.gridLayout_15 = QtWidgets.QGridLayout()
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.label_37 = QtWidgets.QLabel(self.tab_4)
        self.label_37.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_37.setObjectName("label_37")
        self.gridLayout_15.addWidget(self.label_37, 2, 0, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_36.setFont(font)
        self.label_36.setAlignment(QtCore.Qt.AlignCenter)
        self.label_36.setObjectName("label_36")
        self.gridLayout_15.addWidget(self.label_36, 0, 0, 1, 1)
        self.line_17 = QtWidgets.QFrame(self.tab_4)
        self.line_17.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_17.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_17.setObjectName("line_17")
        self.gridLayout_15.addWidget(self.line_17, 1, 0, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_15, 16, 0, 1, 2)
        self.line_13 = QtWidgets.QFrame(self.tab_4)
        self.line_13.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.gridLayout_9.addWidget(self.line_13, 7, 0, 1, 2)
        self.gridLayout_26 = QtWidgets.QGridLayout()
        self.gridLayout_26.setObjectName("gridLayout_26")
        self.label_31 = QtWidgets.QLabel(self.tab_4)
        self.label_31.setMinimumSize(QtCore.QSize(60, 0))
        self.label_31.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.gridLayout_26.addWidget(self.label_31, 0, 0, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_3.setEnabled(False)
        self.lineEdit_3.setMinimumSize(QtCore.QSize(308, 25))
        self.lineEdit_3.setMaximumSize(QtCore.QSize(308, 25))
        self.lineEdit_3.setStyleSheet("color: rgb(0, 0, 0);")
        self.lineEdit_3.setClearButtonEnabled(True)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_26.addWidget(self.lineEdit_3, 0, 1, 1, 1, QtCore.Qt.AlignRight)
        self.gridLayout_9.addLayout(self.gridLayout_26, 6, 0, 1, 2)
        self.line_16 = QtWidgets.QFrame(self.tab_4)
        self.line_16.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_16.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_16.setObjectName("line_16")
        self.gridLayout_9.addWidget(self.line_16, 13, 0, 1, 2)
        self.gridLayout_32 = QtWidgets.QGridLayout()
        self.gridLayout_32.setObjectName("gridLayout_32")
        self.pushButton_12 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_12.setEnabled(False)
        self.pushButton_12.setMinimumSize(QtCore.QSize(184, 40))
        self.pushButton_12.setMaximumSize(QtCore.QSize(1846, 40))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_12.setFont(font)
        self.pushButton_12.setObjectName("pushButton_12")
        self.gridLayout_32.addWidget(self.pushButton_12, 0, 0, 1, 1)
        self.pushButton_13 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_13.setEnabled(False)
        self.pushButton_13.setMinimumSize(QtCore.QSize(184, 40))
        self.pushButton_13.setMaximumSize(QtCore.QSize(1846, 40))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_13.setFont(font)
        self.pushButton_13.setObjectName("pushButton_13")
        self.gridLayout_32.addWidget(self.pushButton_13, 0, 1, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_32, 14, 0, 1, 2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_9.addItem(spacerItem2, 17, 0, 1, 1)
        self.line_14 = QtWidgets.QFrame(self.tab_4)
        self.line_14.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.gridLayout_9.addWidget(self.line_14, 9, 0, 1, 2)
        self.line_8 = QtWidgets.QFrame(self.tab_4)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.gridLayout_9.addWidget(self.line_8, 5, 0, 1, 2)
        self.gridLayout_28 = QtWidgets.QGridLayout()
        self.gridLayout_28.setObjectName("gridLayout_28")
        self.label_34 = QtWidgets.QLabel(self.tab_4)
        self.label_34.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_34.setObjectName("label_34")
        self.gridLayout_28.addWidget(self.label_34, 0, 1, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.tab_4)
        self.label_33.setMinimumSize(QtCore.QSize(70, 0))
        self.label_33.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.gridLayout_28.addWidget(self.label_33, 0, 0, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_28, 10, 0, 1, 2)
        self.gridLayout_22 = QtWidgets.QGridLayout()
        self.gridLayout_22.setObjectName("gridLayout_22")
        self.pushButton_10 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_10.setMinimumSize(QtCore.QSize(100, 20))
        self.pushButton_10.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_10.setObjectName("pushButton_10")
        self.gridLayout_22.addWidget(self.pushButton_10, 0, 0, 1, 1, QtCore.Qt.AlignRight)
        self.gridLayout_9.addLayout(self.gridLayout_22, 0, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_9.addItem(spacerItem3, 15, 0, 1, 1)
        self.line_11.raise_()
        self.line_13.raise_()
        self.line_14.raise_()
        self.line_15.raise_()
        self.line_16.raise_()
        self.line_8.raise_()
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("img/unlock-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_4, icon2, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.gridLayout = QtWidgets.QGridLayout(self.tab_5)
        self.gridLayout.setObjectName("gridLayout")
        self.label_14 = QtWidgets.QLabel(self.tab_5)
        self.label_14.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 0, 0, 1, 1, QtCore.Qt.AlignTop)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("img/about.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_5, icon3, "")
        self.gridLayout_4.addWidget(self.tabWidget, 2, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_4, 0, 1, 1, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 680, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.pushButton.clicked.connect(self.encryption_get_file)
        self.pushButton_3.clicked.connect(self.encryption_location_file)
        self.pushButton_10.clicked.connect(self.decryption_get_file)
        self.pushButton_11.clicked.connect(self.decryption_location_file)
        self.pushButton_4.clicked.connect(self.encryption_clear)
        self.pushButton_13.clicked.connect(self.decryption_clear)
        self.pushButton_2.clicked.connect(self.encrypt)
        self.pushButton_12.clicked.connect(self.decrypt)
        self.label_13.linkActivated.connect(self.open_URL)
        self.label_14.linkActivated.connect(self.open_URL)
        self.label_37.linkActivated.connect(self.open_URL)

    #####ENCRYPTION#####
    def encryption_get_file(self):
        self.lineEdit.setEnabled(True)
        self.pushButton_3.setEnabled(True)
        self.pushButton_4.setEnabled(True)

        Ui_MainWindow.filePath_first = str(QFileDialog.getOpenFileName(options=QFileDialog.ShowDirsOnly))
        Ui_MainWindow.filePath = Ui_MainWindow.filePath_first[2:-6]
        Ui_MainWindow.fileName = Ui_MainWindow.filePath_first[2:-6].split("/")
        self.label_8.setText(Ui_MainWindow.fileName[-1])
        digits = []
        value = int(os.path.getsize(Ui_MainWindow.filePath))
        while value: value, b = divmod(value, 1000); digits.insert(0, b)

        number = ""
        for i in range(len(digits)):
            number = number + str(digits[i]) + "."
        self.label_9.setText(number[0:-1] + " bytes")

    def encryption_location_file(self):
        directory = QFileDialog.getExistingDirectory(options=QFileDialog.ShowDirsOnly)
        if directory:
            Ui_MainWindow.directory = directory
            self.label_11.setText(directory)

        self.pushButton_2.setEnabled(True)
        self.progressBar.setEnabled(True)

    def encryption_clear(self):
        self.label_8.setText("No file selected")
        self.label_9.setText("0 Byte")
        self.lineEdit.setText("")
        self.lineEdit.setEnabled(False)
        self.pushButton_3.setEnabled(False)
        self.label_11.setText("No location yet selected")
        self.pushButton_2.setEnabled(False)
        self.pushButton_4.setEnabled(False)
        self.progressBar.setValue(0)
        self.progressBar.setEnabled(False)
        self.label_12.setText("...")

    def encrypt(self):
        self.progressBar.setValue(0)
        self.action()
        Ui_MainWindow.key = self.lineEdit.text()
        hasher = SHA256.new(Ui_MainWindow.key.encode('utf-8'))
        Ui_MainWindow.password = hasher.digest()

        chunksize = 64 * 1024
        outputFile = "[encrypted]" + Ui_MainWindow.fileName[-1]
        filesize = str(os.path.getsize(Ui_MainWindow.filePath)).zfill(16)
        IV = Random.new().read(16)

        encryptor = AES.new(Ui_MainWindow.password, AES.MODE_CBC, IV)

        with open(Ui_MainWindow.filePath, 'rb') as infile:
            with open(outputFile, 'wb') as outfile:
                outfile.write(filesize.encode('utf-8'))
                outfile.write(IV)

                while True:
                    chunk = infile.read(chunksize)

                    if len(chunk) == 0:
                        break
                    elif len(chunk) % 16 != 0:
                        chunk += b' ' * (16 - (len(chunk) % 16))

                    outfile.write(encryptor.encrypt(chunk))
        source = ('/'.join(map(str, (os.getcwd().split("\\")))) + "/" + outputFile)
        destination = (Ui_MainWindow.directory)+"/"+outputFile
        copyfile(source, destination)
        os.remove(source)
        self.label_12.setText(Ui_MainWindow.fileName[-1] + " was encrypted.")
    #####ENCRYPTION#####

    #####DECRYPTION#####
    def decryption_get_file(self):
        self.lineEdit_3.setEnabled(True)
        self.pushButton_11.setEnabled(True)
        self.pushButton_13.setEnabled(True)

        Ui_MainWindow.filePath_first = str(QFileDialog.getOpenFileName(options=QFileDialog.ShowDirsOnly))
        Ui_MainWindow.filePath = Ui_MainWindow.filePath_first[2:-6]
        Ui_MainWindow.fileName = Ui_MainWindow.filePath_first[2:-6].split("/")
        self.label_28.setText(Ui_MainWindow.fileName[-1])
        digits = []
        value = int(os.path.getsize(Ui_MainWindow.filePath))
        while value: value, b = divmod(value, 1000); digits.insert(0, b)

        number = ""
        for i in range(len(digits)):
            number = number + str(digits[i]) + "."
        self.label_30.setText(number[0:-1] + " bytes")

    def decryption_location_file(self):
        directory = QFileDialog.getExistingDirectory(options=QFileDialog.ShowDirsOnly)
        if directory:
            Ui_MainWindow.directory = directory
            self.label_34.setText(directory)

        self.pushButton_12.setEnabled(True)
        self.progressBar_3.setEnabled(True)

    def decryption_clear(self):
        self.label_28.setText("No file selected")
        self.label_30.setText("0 Byte")
        self.lineEdit_3.setText("")
        self.lineEdit_3.setEnabled(False)
        self.pushButton_11.setEnabled(False)
        self.label_34.setText("No location yet selected")
        self.pushButton_12.setEnabled(False)
        self.pushButton_13.setEnabled(False)
        self.progressBar_3.setValue(0)
        self.progressBar_3.setEnabled(False)
        self.label_36.setText("...")

    def decrypt(self):
        self.progressBar.setValue(0)
        self.action_decrypt()
        Ui_MainWindow.key = self.lineEdit_3.text()
        hasher = SHA256.new(Ui_MainWindow.key.encode('utf-8'))
        Ui_MainWindow.password = hasher.digest()

        chunksize = 64 * 1024
        outputFile = Ui_MainWindow.fileName[-1][11:]
        with open(Ui_MainWindow.filePath, 'rb') as infile:
            filesize = int(infile.read(16))
            IV = infile.read(16)

            decryptor = AES.new(Ui_MainWindow.password, AES.MODE_CBC, IV)

            with open(outputFile, 'wb') as outfile:
                while True:
                    chunk = infile.read(chunksize)

                    if len(chunk) == 0:
                        break

                    outfile.write(decryptor.decrypt(chunk))
                outfile.truncate(filesize)
        source = ('/'.join(map(str, (os.getcwd().split("\\")))) + "/" + outputFile)
        destination = (Ui_MainWindow.directory) + "/" + outputFile
        copyfile(source, destination)
        os.remove(source)
        self.label_36.setText(Ui_MainWindow.fileName[-1][11:] + " was saved.")
    #####DECRYPTION#####

    def open_URL(self):
        webbrowser.open("https://www.tolgaakkapulu.com")

    def action(self):
        self.thread1 = MyThread(1)
        self.thread1.progress.connect(self.setFirstPbar)
        self.thread1.start()

    def setFirstPbar(self, value):
        self.firstStep = value
        self.progressBar.setValue(value)

    def action_decrypt(self):
        self.thread1 = MyThread(1)
        self.thread1.progress.connect(self.setFirstPbar_decrypt)
        self.thread1.start()

    def setFirstPbar_decrypt(self, value):
        self.firstStep = value
        self.progressBar_3.setValue(value)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "File Encryption|Decryption with AES"))
        self.label.setText(_translate("MainWindow", "File Encryption|Decryption with AES"))
        self.pushButton_2.setText(_translate("MainWindow", "Encrypt"))
        self.pushButton_4.setText(_translate("MainWindow", "Clear"))
        self.label_6.setText(_translate("MainWindow", "Select the location of the file to be encrypted..."))
        self.pushButton_3.setText(_translate("MainWindow", "Choose..."))
        self.label_10.setText(_translate("MainWindow", "Location"))
        self.label_11.setText(_translate("MainWindow", "No location yet selected"))
        self.label_5.setText(_translate("MainWindow", "Password"))
        self.label_7.setText(_translate("MainWindow", "Process"))
        self.label_2.setText(_translate("MainWindow", "Select a file to encrypt..."))
        self.pushButton.setText(_translate("MainWindow", "Choose..."))
        self.label_4.setText(_translate("MainWindow", "File Size"))
        self.label_3.setText(_translate("MainWindow", "File Name"))
        self.label_9.setText(_translate("MainWindow", "0 Byte"))
        self.label_8.setText(_translate("MainWindow", "No file selected"))
        self.label_13.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">FED|AES - 2017<br><a href=\"https://www.tolgaakkapulu.com\" target=\"_blank\"><span style=\"color:#00007f\">https://www.tolgaakkapulu.com</span></a></p></body></html>"))
        self.label_12.setText(_translate("MainWindow", "..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Encrypt"))
        self.label_32.setText(_translate("MainWindow", "Select the location of the file to be decrypted..."))
        self.pushButton_11.setText(_translate("MainWindow", "Choose..."))
        self.label_30.setText(_translate("MainWindow", "0 Byte"))
        self.label_29.setText(_translate("MainWindow", "File Size"))
        self.label_28.setText(_translate("MainWindow", "No file selected"))
        self.label_27.setText(_translate("MainWindow", "File Name"))
        self.label_26.setText(_translate("MainWindow", "Select a file to decrypt..."))
        self.label_35.setText(_translate("MainWindow", "Process"))
        self.label_37.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">FED|AES - 2017<br><a href=\"https://www.tolgaakkapulu.com\" target=\"_blank\"><span style=\"color:#00007f\">https://www.tolgaakkapulu.com</span></a></p></body></html>"))
        self.label_36.setText(_translate("MainWindow", "..."))
        self.label_31.setText(_translate("MainWindow", "Password"))
        self.pushButton_12.setText(_translate("MainWindow", "Decrypt"))
        self.pushButton_13.setText(_translate("MainWindow", "Clear"))
        self.label_34.setText(_translate("MainWindow", "No location yet selected"))
        self.label_33.setText(_translate("MainWindow", "Location"))
        self.pushButton_10.setText(_translate("MainWindow", "Choose..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Decrypt"))
        self.label_14.setText(_translate("MainWindow", "<span style=\"color:#00007f\"><b>FED|AES</b></span> was written by Tolga Akkapulu with Python programming language.<br>"
                                                       "It was designed to encrypt and decrypt files securely. AES with 128-bit input<br>"
                                                       " block and 256-bit key length was used to encrypt and decrypt files." 
"<br><br>"
"<span style=\"color:#00007f\"><b>Encryption Part</b></span><br>"
"<span style=\"color:#00007f\"><b>-</b></span> The file to be encrypted is selected.<br>"
"<span style=\"color:#00007f\"><b>-</b></span> The password is entered and it is converted to a key length of 256 bits with<br>"
                                                       "&nbsp;&nbsp;&nbsp;SHA256 in the background.<br>"
"<span style=\"color:#00007f\"><b>-</b></span> The location to save the file to be encrypted is selected.<br>"
"<span style=\"color:#00007f\"><b>-</b></span> The file is encrypted and saved as [encrypted]filename."
"<br><br>"
"<span style=\"color:#00007f\"><b>Decryption Part</b></span><br>"
"<span style=\"color:#00007f\"><b>-</b></span> Encrypted file (such as [encrypted]filename) is selected.<br>"
"<span style=\"color:#00007f\"><b>-</b></span> The correct password for the encrypted file is entered to decrypt.Likewise,<br>"
                                              "&nbsp;&nbsp;&nbsp;this password is converted to a key length of 256 bits with SHA256 in the<br>"
                                              "&nbsp;&nbsp;&nbsp;background.<br>"
"<span style=\"color:#00007f\"><b>-</b></span> The location to save the file to be decrypted is selected.<br>"
"<span style=\"color:#00007f\"><b>-</b></span> The file is decrypted and saved."
"<br><br>"
"<span style=\"color:#00007f\"><b>NOTE :</b></span> In the decryption process, if the correct password is entered, the real<br>"
                                                       "file can be accessed."
                                                       "<br>"
                                                       "<center><a href=\"https://www.tolgaakkapulu.com\" target=\"_blank\"><span style=\"color:#00007f\"><b>https://www.tolgaakkapulu.com</b></span></a></center>"
))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "About"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
